
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: seedrs_development


test:
  <<: *default
  database: seedrs_test


# production:
#   <<: *default
#   database: 